### ISSUE TITLE
re-modify the method in tsfile to fit spark 

### ISSUE THREAD

**Issue by LeiRui** [thulab/tsfile#122]
The branch  '**add_rowGroupReader_support_for_spark**‘  is trying to solve #108 .

But the method below in QueryEngine.java modified by this branch still does not meet the requirement of tsfile-spark-connector:
`    public ArrayList<SeriesSchema> getAllSeriesSchema() {
        return recordReader.getAllSeriesSchema();
    }`

**Detail:**
for example, if the schema of a tsfile is predefined as 's1 s2 s3 s4 s5' and the actual data in the tsfile is a delta_object 'root.car.d1' with 's1 s2 s3', then the method **getAllSeriesSchema**  in branch '**add_rowGroupReader_support_for_spark**‘ would return 's1 s2 s3' with the help of rowGroupReader 
while tsfile-spark-connector is simply expecting the predefined complete schema: 's1 s2 s3 s4 s5' without the need of resorting to rowGroupReader.

**Comment by MyXOF** [comment]
close in #124
