### ISSUE TITLE
重复时间戳写入没有丢弃

### ISSUE THREAD

**Issue by LeiRui** [thulab/tsfile#126]
![issue](https://user-images.githubusercontent.com/33376433/34384632-54d1acb4-eb58-11e7-8105-66b4002c8eba.PNG)
![issue2](https://user-images.githubusercontent.com/33376433/34384633-56c81a94-eb58-11e7-91f0-1b40234e3b63.PNG)

**Comment by qiaojialin** [comment]
not a bug
